from pathlib import Path

from lintul_3.lintul_3 import LINTUL_3
from lintul_3.soilwrappers import Lintul_3_original_WNLP
from pcse.agromanager import AgroManager

SOIL = Lintul_3_original_WNLP
CROP = LINTUL_3
AGROMANAGEMENT = AgroManager
OUTPUT_VARS = ["DVS", "LAI", "WLVG", "WRT", "WSO", "WST", "NNI", "ANLV", "ANRT", "ANSO", "ANST", "WA"]
OUTPUT_INTERVAL = "daily"
OUTPUT_INTERVAL_DAYS = 1
OUTPUT_WEEKDAY = 0
SUMMARY_OUTPUT_VARS = []
TERMINAL_OUTPUT_VARS = []
