from pathlib import Path

from lintul.lintul import LINTUL
from lintul.soilwrappers import Lintul_original_PP_SoilWrapper
from pcse.agromanager import AgroManager

SOIL = Lintul_original_PP_SoilWrapper
CROP = LINTUL
AGROMANAGEMENT = AgroManager
OUTPUT_VARS = ["DVS", "LAI", "WLVG", "WRT", "WSO", "WST", "NNI", "ANLV", "ANRT", "ANSO", "ANST", "WA"]
OUTPUT_INTERVAL = "daily"
OUTPUT_INTERVAL_DAYS = 1
OUTPUT_WEEKDAY = 0
SUMMARY_OUTPUT_VARS = []
TERMINAL_OUTPUT_VARS = []
